/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    {
      type: 'category',
      label: 'Services',
      items: [
        'services/critical-embedded-software',
        {
          type: 'doc',
          id: 'audit',
          label: 'Web3',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [
        'tools/index',
        {
          type: 'category',
          label: '🦀 rocq-of-rust',
          items: [
            'tools/rocq-of-rust/introduction',
            'tools/rocq-of-rust/revm-project',
            'tools/rocq-of-rust/links',
          ],
        },
        {
          type: 'category',
          label: '🪁 rocq-of-solidity',
          items: [
            'tools/rocq-of-solidity/introduction',
            'tools/rocq-of-solidity/specification-project',
          ],
        },
        {
          type: 'category',
          label: '🌱 Garden',
          items: [
            'tools/garden/introduction',
            'tools/garden/rocq-of-llzk',
          ],
        },
        {
          type: 'category',
          label: '🐫 coq-of-ocaml',
          items: [
            'tools/coq-of-ocaml/introduction',
            'tools/coq-of-ocaml/install',
            'tools/coq-of-ocaml/run',
            'tools/coq-of-ocaml/cookbook',
            {
              type: 'category',
              label: 'Language support',
              items: [
                'tools/coq-of-ocaml/language/index',
                'tools/coq-of-ocaml/language/ocaml-core',
                'tools/coq-of-ocaml/language/type-definitions',
                'tools/coq-of-ocaml/language/module-system',
                'tools/coq-of-ocaml/language/gadts',
              ],
            },
            {
              type: 'category',
              label: 'Options',
              items: [
                'tools/coq-of-ocaml/options/index',
                'tools/coq-of-ocaml/options/attributes',
                'tools/coq-of-ocaml/options/configuration',
              ],
            },
            {
              type: 'category',
              label: 'More',
              items: [
                'tools/coq-of-ocaml/more/index',
                'tools/coq-of-ocaml/more/examples',
                'tools/coq-of-ocaml/more/faq',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '◼️ rocq-of-noir',
          items: [
            'tools/rocq-of-noir/introduction',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Company',
      items: [
        'company/about',
        'company/intro',
        'company/claims',
        'company/careers',
        'company/press',
        'company/maps',
      ],
    },
    {
      type: 'category',
      label: '🐻‍❄️ Learn',
      items: [
        'learn/start',
        'learn/install',
        'learn/videos',
      ],
    },
  ],
};
