/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    // {
    //   type: 'category',
    //   label: 'Formal verification',
    //   items: [
    //     'verification/ocaml',
    //     'verification/rust',
    //     'verification/typescript',
    //     'verification/solidity',
    //   ],
    // },
    'audit',
    // {
    //   type: 'category',
    //   label: 'Services',
    //   items: [
    //     'services/ocaml-development',
    //     'services/rust-development',
    //     'services/typescript-development',
    //     'services/solidity-development',
    //   ],
    // },
    {
      type: 'category',
      label: '🛠️ Tools',
      items: [
        {
          type: 'category',
          label: '◼️ coq-of-noir',
          link: {
            type: 'doc',
            id: 'tools/coq-of-noir/introduction',
          },
          items: [
          ],
        },
        {
          type: 'category',
          label: '🐫 coq-of-ocaml',
          link: {
            type: 'doc',
            id: 'tools/coq-of-ocaml/introduction',
          },
          items: [
            'tools/coq-of-ocaml/install',
            'tools/coq-of-ocaml/run',
            'tools/coq-of-ocaml/cookbook',
            {
              type: 'category',
              label: 'Language support',
              link: {
                type: 'doc',
                id: 'tools/coq-of-ocaml/language/index',
              },
              items: [
                'tools/coq-of-ocaml/language/ocaml-core',
                'tools/coq-of-ocaml/language/type-definitions',
                'tools/coq-of-ocaml/language/module-system',
                'tools/coq-of-ocaml/language/gadts',
              ],
            },
            {
              type: 'category',
              label: 'Options',
              link: {
                type: 'doc',
                id: 'tools/coq-of-ocaml/options/index',
              },
              items: [
                'tools/coq-of-ocaml/options/attributes',
                'tools/coq-of-ocaml/options/configuration',
              ],
            },
            {
              type: 'category',
              label: 'More',
              link: {
                type: 'doc',
                id: 'tools/coq-of-ocaml/more/index',
              },
              items: [
                'tools/coq-of-ocaml/more/examples',
                'tools/coq-of-ocaml/more/faq',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '🦀 coq-of-rust',
          link: {
            type: 'doc',
            id: 'tools/coq-of-rust/introduction',
          },
          items: [
            'tools/coq-of-rust/revm-project',
            'tools/coq-of-rust/links',
          ],
        },
        {
          type: 'category',
          label: '🪁 coq-of-solidity',
          link: {
            type: 'doc',
            id: 'tools/coq-of-solidity/introduction',
          },
          items: [
            'tools/coq-of-solidity/specification-project',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '👥 Company',
      items: [
        'company/about',
        'company/intro',
        'company/claims',
        'company/careers',
        'company/press',
        'company/maps',
      ],
    },
    {
      type: 'category',
      label: '🤓 Learn',
      items: [
        'learn/start',
        'learn/install',
      ],
    },
  ],
};
